spring.application.name=web

spring.datasource.postgres.jdbc-url=jdbc:postgresql://localhost:5432/donutshop
spring.datasource.postgres.username=root
spring.datasource.postgres.password=4509

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=donutshop