spring.application.name=web

spring.datasource.url=jdbc:postgresql://localhost:5432/donutshop
spring.datasource.username=root
spring.datasource.password=4509

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mongodb.uri=mongodb://localhost:27017/donutshop

server.error.whitelabel.enabled=false